### ISSUE TITLE
AttributeError: 'MediaInfo' object has no attribute 'xml_dom'

### ISSUE THREAD

**Issue by medariox** [ratoaq2/knowit#20]
```
2019-06-07 02:17:44 ERROR    SHOWQUEUE-REFRESH :: [721c3f8] 71446: Error while refreshing show Money Heist. Error: 'MediaInfo' object has no attribute 'xml_dom'
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 688, in run
    self.show.refresh_dir()
  File "/app/medusa/medusa/tv/series.py", line 1792, in refresh_dir
    self.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 1053, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1397, in make_ep_from_file
    cur_ep.update_status_quality(filepath)
  File "/app/medusa/medusa/tv/episode.py", line 2040, in update_status_quality
    new_quality = Quality.name_quality(filepath, self.series.is_anime)
  File "/app/medusa/medusa/common.py", line 284, in name_quality
    return Quality._extend_quality(name)
  File "/app/medusa/medusa/common.py", line 383, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/app/medusa/medusa/common.py", line 405, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/app/medusa/ext/knowit/api.py", line 70, in know
    raise KnowitException(debug_info(context=context, exc_info=True))
  File "/app/medusa/ext/knowit/api.py", line 121, in debug_info
    lines.append(debug_data())
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 289, in debug_data
    xml = ensure_text(ElementTree.tostring(media_info.xml_dom)).replace('\r', '').replace('\n', '')
AttributeError: 'MediaInfo' object has no attribute 'xml_dom'
```

Only occurs with `pymediainfo >= 4.0` because of API changes.

**Comment by ratoaq2** [comment]
mediainfo provider since latest release was changed to use json output instead of xml. This issue is therefore not current anymore
