### ISSUE TITLE
RuntimeError while processing video with Medusa

### ISSUE THREAD

**Issue by rdeherder** [ratoaq2/knowit#200]
I'm running Medusa in a docker container. Medusa uses knowit and while processing a list of video's I got some runtime errors with knowit. Hopefully you can do something with this log entry.
If you say it's a Medusa issue I'll report it there.

```
2024-12-25 09:49:56 WARNING	SHOWQUEUE-REFRESH :: An error occurred while parsing: /video/Series/One-Punch Man/One-Punch Man - S02E11 - Everyone’s Dignity.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
|                   libmediainfo.so.0                   |
|                        v23.11                         |
|                                                       |
|                        ffprobe                        |
|                        v6.1.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 91, in extract_info
    return self._execute(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/pymediainfo/__init__.py", line 496, in parse
    raise RuntimeError(
RuntimeError: An error occured while opening /video/Series/One-Punch Man/One-Punch Man - S02E11 - Everyone’s Dignity.mkv with libmediainfo
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 91, in extract_info
    return self._execute(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/pymediainfo/__init__.py", line 496, in parse
    raise RuntimeError(
RuntimeError: An error occured while opening /video/Series/One-Punch Man/One-Punch Man - S02E11 - Everyone’s Dignity.mkv with libmediainfo
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/medusa/medusa/common.py", line 416, in quality_from_file_meta
    knowledge = knowit.know(file_path)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/api.py", line 65, in know
    raise KnowitException(debug_info(context=context, exc_info=True))
knowit.api.KnowitException: +-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
|                   libmediainfo.so.0                   |
|                        v23.11                         |
|                                                       |
|                        ffprobe                        |
|                        v6.1.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/app/medusa/ext/knowit/api.py", line 59, in know
    result = provider.describe(video_path, context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 91, in extract_info
    return self._execute(filename)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/knowit/providers/mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/medusa/ext/pymediainfo/__init__.py", line 496, in parse
    raise RuntimeError(
RuntimeError: An error occured while opening /video/Series/One-Punch Man/One-Punch Man - S02E11 - Everyone’s Dignity.mkv with libmediainfo
+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
```

**Comment by ratoaq2** [comment]
well, mediainfo ( https://mediaarea.net/en/MediaInfo ) is crashing when trying to open this specific file. 

Maybe try a newer mediainfo version. Or a different provider
