### ISSUE TITLE
Knowit in Medusa hitting a RuntimeErrror due to libmediainfo not being able to handle file

### ISSUE THREAD

**Issue by akosasante** [ratoaq2/knowit#22]
Knowit throws a RuntimeError whenever it tries to use the MediaInfo library to parse files. It only happens with some files, so I'm not sure if size or something else is the cause. Let me know what other information I can provide

<details><summary>Logs:</summary>
<p>
```
KnowIt reported:

+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                   libmediainfo.so.0                   |
|                        v0.7.91                        |
|                                                       |
|                        ffprobe                        |
|                        v3.2.14                        |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/opt/medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/opt/medusa/ext/knowit/providers/mediainfo.py", line 285, in describe
    media_info = self.executor.extract_info(video_path)
  File "/opt/medusa/ext/knowit/providers/mediainfo.py", line 100, in extract_info
    return self._execute(filename)
  File "/opt/medusa/ext/knowit/providers/mediainfo.py", line 167, in _execute
    return MediaInfo.parse(filename, library_file=self.location)
  File "/opt/medusa/lib/pymediainfo/__init__.py", line 266, in parse
    " with libmediainfo".format(filename))
RuntimeError: An eror occured while opening /media/******/TV/All Elite Wrestling Dynamite/Season 1/All Elite Wrestling Dynamite - S01E01 - #1 - Capital One Arena in Washington, DC.mkv with libmediainfo
+-------------------------------------------------------+
```
</p>
</details>

**Comment by akosasante** [comment]
Interestingly, when I run the `knowit` cli command directly, I don't get an error, but the there is much less returned info than for other files:

```
knowit -E -v -p mediainfo "/media/My Passport/TV/All Elite Wrestling Dynamite/Season 1/All Elite Wrestling Dynamite - S01E01 - #1 - Capital One Arena in Washington, DC.mkv"
For: /media/My Passport/TV/All Elite Wrestling Dynamite/Season 1/All Elite Wrestling Dynamite - S01E01 - #1 - Capital One Arena in Washington, DC.mkv
Detected os: unix
MediaInfo library detected: /usr/local/mediainfo/lib/libmediainfo.so.0
Detected os: unix
FFmpeg cli detected: ffprobe
Handling general track
Knowit 0.2.4 found:
{
    "path": "/media/My Passport/TV/All Elite Wrestling Dynamite/Season 1/All Elite Wrestling Dynamite - S01E01 - #1 - Capital One Arena in Washington, DC.mkv",
    "container": "mkv",
    "size": 2370231659,
    "provider": "/usr/local/mediainfo/lib/libmediainfo.so.0"
}
```

**Comment by akosasante** [comment]
Hmm, I also posted in pymedia repo: https://github.com/sbraz/pymediainfo/issues/74

It looks like the version of libmediainfo is too old. But 0.7.9 is the most recent version available in the debian package manager on Debian Stretch (v. 9.11). Is there any way to pull in a newer version of libmediainfo?

**Comment by ratoaq2** [comment]
Medusa is using latest knowit development version. Your cli is using 0.2.4 instead of 0.3-dev

In the latest development version, the issue related to old mediainfo is fixed. 

And it's quite normal that some files arr a bit corrupted that either mediainfo or ffmpeg can't extract their metadata.

**Comment by akosasante** [comment]
Ah, maybe I inadvertenly am overriding medusa's version then? Should I uninstall knowit via apt in that case? I installed it with hopes of fixing/debuggingn the errors I was seeing in Medusa's logs.

**Comment by akosasante** [comment]
FWIW, installing/building the mediainfo version from the repo https://mediaarea.net/en/Repos seems to have cleared up the issue so far. Thanks again!
