### ISSUE TITLE
Medusa / Synology - An error occurred while parsing

### ISSUE THREAD

**Issue by brandnewant** [ratoaq2/knowit#25]
2020-10-22 09:20:28 WARNING  SHOWQUEUE-REFRESH :: [b352bb6] An error occurred while parsing: /volume1/VDrive/TV/The Great American Baking Show/The.Great.American.Baking.Show.S01E02.Cake.Week.mkv
KnowIt reported:
```
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/ext/knowit/providers/enzyme.py", line 116, in describe
    ff = self.extract_info(video_path)
  File "/volume1/@appstore/medusa/var/Medusa/ext/knowit/providers/enzyme.py", line 110, in extract_info
    return todict(enzyme.MKV(f))
  File "/volume1/@appstore/medusa/var/Medusa/ext/enzyme/mkv.py", line 42, in __init__
    raise MalformedMKVError('No Segment found')
enzyme.exceptions.MalformedMKVError: No Segment found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/volume1/@appstore/medusa/var/Medusa/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/medusa/var/Medusa/ext/knowit/providers/enzyme.py", line 131, in describe
    raise MalformedFileError
knowit.provider.MalformedFileError

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
```

**Comment by ratoaq2** [comment]
Knowit is a wrapper around enzyme, mediainfo, ffmpeg and mkvmerge. If any of these tools are unable to inspect the media file (e.g.: out of specification or corrupted), an exception is thrown and knowit wraps the exception in this way with additional information.

In this case, the Enzyme reports this MKV as invalid, corrupted or out of specification. You might try different providers like mediainfo or ffmpeg or mkvmerge and see if they are more resilient.
