### ISSUE TITLE
Error in Medusa

### ISSUE THREAD

**Issue by MikeyMan83** [ratoaq2/knowit#26]
Hi All,

I’m using medusa; and got back the below errors in the logs.
Any ideas?

```
2020-11-15` 19:25:09 WARNING  SHOWQUEUE-REFRESH :: [f39927e] An error occurred while parsing: /volume1/Series/American Crime Story/Season 01/S01E03 - The Dream Team.mkv
KnowIt reported:
+-------------------------------------------------------+
|                   KnowIt 0.3.0-dev                    |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                         3.2.1                         |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
{
    "info": {
        "duration": "0:45:40", 
        "muxing_app": "libebml v1.3.3 + libmatroska v1.4.4", 
        "date_utc": "2016-02-18 07:47:29", 
        "writing_app": "mkvmerge v8.8.0 ('Wind at my back') 64bit"
    }, 
    "video_tracks": [
        {
            "forced": false, 
            "display_height": 718, 
            "language": "eng", 
            "default": true, 
            "aspect_ratio_type": 0, 
            "enabled": true, 
            "number": 1, 
            "crop": {}, 
            "height": 718, 
            "width": 1280, 
            "codec_id": "V_MPEG4/ISO/AVC", 
            "stereo_mode": 0, 
            "lacing": false, 
            "type": 1, 
            "display_width": 1280, 
            "interlaced": false
        }
    ], 
    "tags": [
        {
            "simpletags": [
                {
                    "default": 1, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "3946932"
                }, 
                {
                    "default": 1, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "00:45:40.822000000"
                }, 
                {
                    "default": 1, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "65714"
                }, 
                {
                    "default": 1, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "1352229972"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v8.8.0 ('Wind at my back') 64bit"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2016-02-18 07:47:29"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TargetTypeValue", 
                    "level": 4, 
                    "data": 50, 
                    "position": 1484493929, 
                    "type": 1, 
                    "id": 26826, 
                    "size": 1
                }, 
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 13770436789081999283, 
                    "position": 1484493933, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 8
                }, 
                {
                    "name": "TargetType", 
                    "level": 4, 
                    "data": "MOVIE", 
                    "position": 1484493944, 
                    "type": 3, 
                    "id": 25546, 
                    "size": 5
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": 1, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "384000"
                }, 
                {
                    "default": 1, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "00:45:40.800000000"
                }, 
                {
                    "default": 1, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "85650"
                }, 
                {
                    "default": 1, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "131558400"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v8.8.0 ('Wind at my back') 64bit"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2016-02-18 07:47:29"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TargetTypeValue", 
                    "level": 4, 
                    "data": 50, 
                    "position": 1484494346, 
                    "type": 1, 
                    "id": 26826, 
                    "size": 1
                }, 
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 6160314264252544664, 
                    "position": 1484494350, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 8
                }, 
                {
                    "name": "TargetType", 
                    "level": 4, 
                    "data": "MOVIE", 
                    "position": 1484494361, 
                    "type": 3, 
                    "id": 25546, 
                    "size": 5
                }
            ]
        }, 
        {
            "simpletags": [
                {
                    "default": 1, 
                    "name": "BPS", 
                    "language": "eng", 
                    "string": "129"
                }, 
                {
                    "default": 1, 
                    "name": "DURATION", 
                    "language": "eng", 
                    "string": "00:45:38.667000000"
                }, 
                {
                    "default": 1, 
                    "name": "NUMBER_OF_FRAMES", 
                    "language": "eng", 
                    "string": "998"
                }, 
                {
                    "default": 1, 
                    "name": "NUMBER_OF_BYTES", 
                    "language": "eng", 
                    "string": "44363"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_WRITING_APP", 
                    "language": "eng", 
                    "string": "mkvmerge v8.8.0 ('Wind at my back') 64bit"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_WRITING_DATE_UTC", 
                    "language": "eng", 
                    "string": "2016-02-18 07:47:29"
                }, 
                {
                    "default": 1, 
                    "name": "_STATISTICS_TAGS", 
                    "language": "eng", 
                    "string": "BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES"
                }
            ], 
            "targets": [
                {
                    "name": "TargetTypeValue", 
                    "level": 4, 
                    "data": 50, 
                    "position": 1484494761, 
                    "type": 1, 
                    "id": 26826, 
                    "size": 1
                }, 
                {
                    "name": "TagTrackUID", 
                    "level": 4, 
                    "data": 6226512946639166606, 
                    "position": 1484494765, 
                    "type": 1, 
                    "id": 25541, 
                    "size": 8
                }, 
                {
                    "name": "TargetType", 
                    "level": 4, 
                    "data": "MOVIE", 
                    "position": 1484494776, 
                    "type": 3, 
                    "id": 25546, 
                    "size": 5
                }
            ]
        }
    ], 
    "chapters": [], 
    "audio_tracks": [
        {
            "forced": false, 
            "language": "eng", 
            "default": true, 
            "output_sampling_frequency": 48000.0, 
            "enabled": true, 
            "number": 2, 
            "sampling_frequency": 48000.0, 
            "channels": 6, 
            "codec_id": "A_AC3", 
            "lacing": true, 
            "type": 2
        }
    ], 
    "recurse_seek_head": false, 
    "subtitle_tracks": [
        {
            "forced": false, 
            "language": "eng", 
            "default": true, 
            "enabled": true, 
            "number": 3, 
            "codec_id": "S_TEXT/UTF8", 
            "lacing": false, 
            "type": 17
        }
    ]
}
+-------------------------------------------------------+
Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/api.py", line 64, in know
    result = provider.describe(video_path, context)
  File "/volume1/@appstore/sickbeard-custom/var/SickBeard/ext/knowit/providers/enzyme.py", line 135, in describe
    video_path=video_path, version=enzyme.__version__, data=json.dumps(data))
  File "/usr/local/python/lib/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/python/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/python/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/python/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.timedelta(0, 2740, 822000) is not JSON serializable
```

**Comment by ratoaq2** [comment]
Same fix as #24
