### ISSUE TITLE
Warning ShowQueue-Refresh

### ISSUE THREAD

**Issue by WarEagleUS21** [ratoaq2/knowit#42]
Getting the following error message below:

2022-06-02 06:15:13 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x22 - And Now We Come to the End.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:15:11 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x21 - Lying Doesn't Protect You From the Truth.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:15:08 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x20 - End of the Day, Anything Can Happen.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:15:06 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x19 - Like a Phoenix Rising From the Ashes.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:15:04 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x18 - Judge Not, For You Will Be Judged.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:15:02 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x17 - If You Love Someone, Set Them Free.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:14:59 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x16 - May Your Choices Reflect Hope, Not Fear.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:14:57 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x15 - Things Meant to Be Bent Not Broken.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:14:55 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x14 - All the Things That Could Have Been.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:14:53 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x13 - Reality Leaves a Lot to the Imagination.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:14:51 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x12 - What You Don't Know Can't Hurt You.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:14:49 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x11 - The Things We Thought We Left Behind.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

+-------------------------------------------------------+
|      Please report any bug or feature request at      |
|       https://github.com/ratoaq2/knowit/issues.       |
+-------------------------------------------------------+
2022-06-02 06:14:46 WARNING  SHOWQUEUE-REFRESH :: [ad2c7ad] An error occurred while parsing: L:\TV Shows\Chicago Med (2015)\Season 07\Chicago Med - 7x10 - No Good Deed Goes Unpunished… in Chicago.mkv
KnowIt reported:
+-------------------------------------------------------+
|                     KnowIt 0.4.0                      |
+-------------------------------------------------------+
|                      pymediainfo                      |
|                                                       |
| edusa\Medusa\lib\native\windows\x86_64\MediaInfo.dll  |
|                        v0.7.89                        |
|                                                       |
|                                                       |
|                                                       |
|                        enzyme                         |
|                         0.4.2                         |
+-------------------------------------------------------+
|                   profile: default                    |
+-------------------------------------------------------+
Traceback (most recent call last):
  File "C:\Medusa\Medusa\ext\knowit\api.py", line 59, in know
    result = provider.describe(video_path, context)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 284, in describe
    data = self.executor.extract_info(video_path)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 91, in extract_info
    return self._execute(filename)
  File "C:\Medusa\Medusa\ext\knowit\providers\mediainfo.py", line 157, in _execute
    return json.loads(MediaInfo.parse(filename, library_file=self.location, output='JSON'))
  File "C:\Medusa\Python\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Medusa\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Medusa\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by ratoaq2** [comment]
Same fix as #43
