### ISSUE TITLE
returned non-zero exit status -11

### ISSUE THREAD

**Issue by OmgImAlexis** [ratoaq2/knowit#7]
```
2017-08-23 16:49:45 ERROR    SHOWQUEUE-ADD :: [49e9fc3] Error searching dir for episodes: 
Traceback (most recent call last):
  File "/app/medusa/medusa/show_queue.py", line 562, in run
    self.show.load_episodes_from_dir()
  File "/app/medusa/medusa/tv/series.py", line 919, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/app/medusa/medusa/tv/series.py", line 1345, in make_ep_from_file
    filepath)
  File "/app/medusa/medusa/tv/series.py", line 1214, in should_refresh_file
    new_quality = Quality.name_quality(filepath, anime)
  File "/app/medusa/medusa/common.py", line 302, in name_quality
    return Quality._extend_quality(name)
  File "/app/medusa/medusa/common.py", line 401, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/app/medusa/medusa/common.py", line 422, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/app/medusa/lib/knowit/api.py", line 49, in know
    return provider.describe(video_path, context)
  File "/app/medusa/lib/knowit/providers/mediainfo.py", line 330, in describe
    data = self.executor.extract_info(video_path).to_data()
  File "/app/medusa/lib/knowit/providers/mediainfo.py", line 89, in extract_info
    xml = self._execute(filename)
  File "/app/medusa/lib/knowit/providers/mediainfo.py", line 122, in _execute
    return check_output([self.location, '--Output=XML', '--Full', filename])
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '[u'mediainfo', u'--Output=XML', u'--Full', u'/mnt/user/TV Shows/Parks and Recreation/Parks and Recreation - S03E05 - Media Blitz 1080p HDTV.mp4']' returned non-zero exit status -11
```

```
mediainfo --Output=XML --Full '/mnt/user/TV Shows/Parks and Recreation/Parks and Recreation - S03E05 - Media Blitz 1080p HDTV.mp4'
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Mediainfo version="0.7.90">
  <File>
    <track type="General">
      <Count>322</Count>
      <Count_of_stream_of_this_kind>1</Count_of_stream_of_this_kind>
      <Kind_of_stream>General</Kind_of_stream>
      <Kind_of_stream>General</Kind_of_stream>
      <Stream_identifier>0</Stream_identifier>
      <Count_of_video_streams>1</Count_of_video_streams>
      <Count_of_audio_streams>1</Count_of_audio_streams>
      <Video_Format_List>HEVC</Video_Format_List>
      <Video_Format_WithHint_List>HEVC</Video_Format_WithHint_List>
      <Codecs_Video>HEVC</Codecs_Video>
      <Audio_Format_List>AAC</Audio_Format_List>
      <Audio_Format_WithHint_List>AAC</Audio_Format_WithHint_List>
      <Audio_codecs>AAC LC-SBR</Audio_codecs>
      <Audio_Language_List>English</Audio_Language_List>
      <Complete_name>/mnt/user/TV Shows/Parks and Recreation/Parks and Recreation - S03E05 - Media Blitz 1080p HDTV.mp4</Complete_name>
      <Folder_name>/mnt/user/TV Shows/Parks and Recreation</Folder_name>
      <File_name>Parks and Recreation - S03E05 - Media Blitz 1080p HDTV</File_name>
      <File_extension>mp4</File_extension>
      <Format>MPEG-4</Format>
      <Format>MPEG-4</Format>
      <Format_Extensions_usually_used>mp4 m4v m4a m4b m4p 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma f4v</Format_Extensions_usually_used>
      <Commercial_name>MPEG-4</Commercial_name>
      <Format_profile>Base Media / Version 2</Format_profile>
      <Internet_media_type>video/mp4</Internet_media_type>
      <Codec_ID>mp42</Codec_ID>
      <Codec_ID>mp42 (isom/iso2/mp41)</Codec_ID>
      <Codec_ID_Url>http://www.apple.com/quicktime/download/standalone.html</Codec_ID_Url>
      <CodecID_Compatible>isom/iso2/mp41</CodecID_Compatible>
      <Codec>MPEG-4</Codec>
      <Codec>MPEG-4</Codec>
      <Codec_Extensions_usually_used>mp4 m4v m4a m4b m4p 3gpp 3gp 3gpp2 3g2 k3g jpm jpx mqv ismv isma f4v</Codec_Extensions_usually_used>
      <File_size>265886821</File_size>
      <File_size>254 MiB</File_size>
      <File_size>254 MiB</File_size>
      <File_size>254 MiB</File_size>
      <File_size>254 MiB</File_size>
      <File_size>253.6 MiB</File_size>
      <Duration>1280256</Duration>
      <Duration>21 min 20 s</Duration>
      <Duration>21 min 20 s 256 ms</Duration>
      <Duration>21 min 20 s</Duration>
      <Duration>00:21:20.256</Duration>
      <Duration>00:21:20;13</Duration>
      <Duration>00:21:20.256 (00:21:20;13)</Duration>
      <Overall_bit_rate_mode>VBR</Overall_bit_rate_mode>
      <Overall_bit_rate_mode>Variable</Overall_bit_rate_mode>
      <Overall_bit_rate>1661460</Overall_bit_rate>
      <Overall_bit_rate>1 661 kb/s</Overall_bit_rate>
      <Frame_rate>23.976</Frame_rate>
      <Frame_rate>23.976 FPS</Frame_rate>
      <Frame_count>30695</Frame_count>
      <Stream_size>856473</Stream_size>
      <Stream_size>836 KiB (0%)</Stream_size>
      <Stream_size>836 KiB</Stream_size>
      <Stream_size>836 KiB</Stream_size>
      <Stream_size>836 KiB</Stream_size>
      <Stream_size>836.4 KiB</Stream_size>
      <Stream_size>836 KiB (0%)</Stream_size>
      <Proportion_of_this_stream>0.00322</Proportion_of_this_stream>
      <HeaderSize>856465</HeaderSize>
      <DataSize>265030356</DataSize>
      <FooterSize>0</FooterSize>
      <IsStreamable>Yes</IsStreamable>
      <Encoded_date>UTC 2036-02-06 06:28:16</Encoded_date>
      <Tagged_date>UTC 2036-02-06 06:28:16</Tagged_date>
      <File_last_modification_date>UTC 2016-03-23 16:32:05</File_last_modification_date>
      <File_last_modification_date__local_>2016-03-24 03:02:05</File_last_modification_date__local_>
      <Writing_application>HandBrake 0.10.2 2015060900</Writing_application>
      <Writing_application>HandBrake 0.10.2 2015060900</Writing_application>
    </track>
    <track type="Video">
      <Count>334</Count>
      <Count_of_stream_of_this_kind>1</Count_of_stream_of_this_kind>
      <Kind_of_stream>Video</Kind_of_stream>
      <Kind_of_stream>Video</Kind_of_stream>
      <Stream_identifier>0</Stream_identifier>
      <StreamOrder>0</StreamOrder>
      <ID>1</ID>
      <ID>1</ID>
      <Format>HEVC</Format>
      <Format_Info>High Efficiency Video Coding</Format_Info>
      <Format_Url>http://www.itu.int</Format_Url>
      <Commercial_name>HEVC</Commercial_name>
      <Format_profile>Main@L4@Main</Format_profile>
      <Internet_media_type>video/H265</Internet_media_type>
      <Codec_ID>hev1</Codec_ID>
      <Codec_ID_Info>High Efficiency Video Coding</Codec_ID_Info>
      <Codec_ID_Url>http://www.itu.int/</Codec_ID_Url>
      <Codec>HEVC</Codec>
      <Codec>HEVC</Codec>
      <Codec_CC>hev1</Codec_CC>
      <Codec_profile>Main@L4@Main</Codec_profile>
      <Duration>1280238</Duration>
      <Duration>21 min 20 s</Duration>
      <Duration>21 min 20 s 238 ms</Duration>
      <Duration>21 min 20 s</Duration>
      <Duration>00:21:20.238</Duration>
      <Duration>00:21:20;13</Duration>
      <Duration>00:21:20.238 (00:21:20;13)</Duration>
      <Bit_rate>1464128</Bit_rate>
      <Bit_rate>1 464 kb/s</Bit_rate>
      <Width>1912</Width>
      <Width>1 912 pixels</Width>
      <Height>1076</Height>
      <Height>1 076 pixels</Height>
      <Stored_Height>1080</Stored_Height>
      <Sampled_Width>1912</Sampled_Width>
      <Sampled_Height>1076</Sampled_Height>
      <Pixel_aspect_ratio>1.000</Pixel_aspect_ratio>
      <Display_aspect_ratio>1.777</Display_aspect_ratio>
      <Display_aspect_ratio>16:9</Display_aspect_ratio>
      <Rotation>0.000</Rotation>
      <Frame_rate_mode>VFR</Frame_rate_mode>
      <Frame_rate_mode>Variable</Frame_rate_mode>
      <Frame_rate>23.976</Frame_rate>
      <Frame_rate>23.976 (24000/1001) FPS</Frame_rate>
      <FrameRate_Num>24000</FrameRate_Num>
      <FrameRate_Den>1001</FrameRate_Den>
      <Minimum_frame_rate>23.974</Minimum_frame_rate>
      <Minimum_frame_rate>23.974 FPS</Minimum_frame_rate>
      <Maximum_frame_rate>23.981</Maximum_frame_rate>
      <Maximum_frame_rate>23.981 FPS</Maximum_frame_rate>
      <Frame_count>30695</Frame_count>
      <Resolution>8</Resolution>
      <Resolution>8 bits</Resolution>
      <Colorimetry>4:2:0</Colorimetry>
      <Color_space>YUV</Color_space>
      <Chroma_subsampling>4:2:0</Chroma_subsampling>
      <Chroma_subsampling>4:2:0</Chroma_subsampling>
      <Bit_depth>8</Bit_depth>
      <Bit_depth>8 bits</Bit_depth>
      <Bits__Pixel_Frame_>0.030</Bits__Pixel_Frame_>
      <Stream_size>234304203</Stream_size>
      <Stream_size>223 MiB (88%)</Stream_size>
      <Stream_size>223 MiB</Stream_size>
      <Stream_size>223 MiB</Stream_size>
      <Stream_size>223 MiB</Stream_size>
      <Stream_size>223.4 MiB</Stream_size>
      <Stream_size>223 MiB (88%)</Stream_size>
      <Proportion_of_this_stream>0.88122</Proportion_of_this_stream>
      <Writing_library>x265 - 1.5:[Windows][GCC 4.9.0][64 bit]</Writing_library>
      <Writing_library>x265 1.5:[Windows][GCC 4.9.0][64 bit]</Writing_library>
      <Encoded_Library_Name>x265</Encoded_Library_Name>
      <Encoded_Library_Version>1.5:[Windows][GCC 4.9.0][64 bit]</Encoded_Library_Version>
      <Encoding_settings>wpp / ctu=64 / tu-intra-depth=1 / tu-inter-depth=1 / me=1 / subme=2 / merange=57 / no-rect / no-amp / max-merge=2 / temporal-mvp / no-early-skip / no-fast-cbf / rdpenalty=0 / no-tskip / no-tskip-fast / strong-intra-smoothing / no-lossless / no-cu-lossless / no-constrained-intra / no-fast-intra / open-gop / interlace=0 / keyint=240 / min-keyint=24 / scenecut=40 / rc-lookahead=20 / bframes=4 / bframe-bias=0 / b-adapt=2 / ref=3 / weightp / no-weightb / aq-mode=1 / aq-strength=1.00 / cbqpoffs=0 / crqpoffs=0 / rd=3 / psy-rd=0.30 / psy-rdoq=0.00 / signhide / lft / sao / no-sao-non-deblock / b-pyramid / cutree / rc=crf / crf=22.0 / qcomp=0.60 / qpmin=0 / qpmax=51 / qpstep=4 / ipratio=1.40 / pbratio=1.30</Encoding_settings>
      <Encoded_date>UTC 2036-02-06 06:28:16</Encoded_date>
      <Tagged_date>UTC 2036-02-06 06:28:16</Tagged_date>
      <Color_range>Limited</Color_range>
      <colour_description_present>Yes</colour_description_present>
      <Color_primaries>BT.709</Color_primaries>
      <Transfer_characteristics>BT.709</Transfer_characteristics>
      <Matrix_coefficients>BT.709</Matrix_coefficients>
    </track>
    <track type="Audio">
      <Count>272</Count>
      <Count_of_stream_of_this_kind>1</Count_of_stream_of_this_kind>
      <Kind_of_stream>Audio</Kind_of_stream>
      <Kind_of_stream>Audio</Kind_of_stream>
      <Stream_identifier>0</Stream_identifier>
      <StreamOrder>1</StreamOrder>
      <ID>2</ID>
      <ID>2</ID>
      <Format>AAC</Format>
      <Format_Info>Advanced Audio Codec</Format_Info>
      <Commercial_name>AAC</Commercial_name>
      <Format_profile>HE-AAC / LC</Format_profile>
      <Format_settings__SBR>Yes (Implicit)</Format_settings__SBR>
      <Format_settings__SBR>Yes (Implicit)</Format_settings__SBR>
      <Codec_ID>40</Codec_ID>
      <Codec>AAC LC-SBR</Codec>
      <Codec>AAC LC-SBR</Codec>
      <Codec_Family>AAC</Codec_Family>
      <Codec_CC>40</Codec_CC>
      <Duration>1280256</Duration>
      <Duration>21 min 20 s</Duration>
      <Duration>21 min 20 s 256 ms</Duration>
      <Duration>21 min 20 s</Duration>
      <Duration>00:21:20.256</Duration>
      <Duration>00:21:44:14</Duration>
      <Duration>00:21:20.256 (00:21:44:14)</Duration>
      <Bit_rate_mode>VBR</Bit_rate_mode>
      <Bit_rate_mode>Variable</Bit_rate_mode>
      <Bit_rate>192000</Bit_rate>
      <Bit_rate>192 kb/s</Bit_rate>
      <Channel_s_>2</Channel_s_>
      <Channel_s_>2 channels</Channel_s_>
      <Channel_s__Original>6</Channel_s__Original>
      <Channel_s__Original>6 channels</Channel_s__Original>
      <Channel_positions>Front: L C R, Side: L R, LFE</Channel_positions>
      <Channel_positions>3/2/0.1</Channel_positions>
      <ChannelLayout>C L R Ls Rs LFE</ChannelLayout>
      <Samples_per_frame>1024</Samples_per_frame>
      <Sampling_rate>48000 / 24000</Sampling_rate>
      <Sampling_rate>48.0 kHz / 24.0 kHz</Sampling_rate>
      <Samples_count>61452288</Samples_count>
      <Frame_rate>23.438</Frame_rate>
      <Frame_rate>23.438 FPS (1024 spf)</Frame_rate>
      <Frame_count>30006</Frame_count>
      <Compression_mode>Lossy</Compression_mode>
      <Compression_mode>Lossy</Compression_mode>
      <Stream_size>30726145</Stream_size>
      <Stream_size>29.3 MiB (12%)</Stream_size>
      <Stream_size>29 MiB</Stream_size>
      <Stream_size>29 MiB</Stream_size>
      <Stream_size>29.3 MiB</Stream_size>
      <Stream_size>29.30 MiB</Stream_size>
      <Stream_size>29.3 MiB (12%)</Stream_size>
      <Proportion_of_this_stream>0.11556</Proportion_of_this_stream>
      <Title>Surround / Surround</Title>
      <Language>en</Language>
      <Language>English</Language>
      <Language>English</Language>
      <Language>en</Language>
      <Language>eng</Language>
      <Language>en</Language>
      <Default>Yes</Default>
      <Default>Yes</Default>
      <Alternate_group>1</Alternate_group>
      <Alternate_group>1</Alternate_group>
      <Encoded_date>UTC 2036-02-06 06:28:16</Encoded_date>
      <Tagged_date>UTC 2036-02-06 06:28:16</Tagged_date>
    </track>
  </File>
</Mediainfo>
```

**Comment by ratoaq2** [comment]
Mediainfo provider since last release uses JSON instead of XML. If the issue persists, please create a new issue
