### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by fernandog** [ratoaq2/knowit#8]
From Medusa issue:

```
2017-07-17 15:41:48 ERROR    SHOWQUEUE-ADD :: [6b7e935] Error searching dir for episodes: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/share/www/Medusa/medusa/show_queue.py", line 562, in run
    self.show.load_episodes_from_dir()
  File "/usr/local/share/www/Medusa/medusa/tv/series.py", line 919, in load_episodes_from_dir
    cur_episode = self.make_ep_from_file(os.path.join(self.location, media_file))
  File "/usr/local/share/www/Medusa/medusa/tv/series.py", line 1345, in make_ep_from_file
    filepath)
  File "/usr/local/share/www/Medusa/medusa/tv/series.py", line 1214, in should_refresh_file
    new_quality = Quality.name_quality(filepath, anime)
  File "/usr/local/share/www/Medusa/medusa/common.py", line 302, in name_quality
    return Quality._extend_quality(name)
  File "/usr/local/share/www/Medusa/medusa/common.py", line 401, in _extend_quality
    quality = Quality.quality_from_file_meta(file_path)
  File "/usr/local/share/www/Medusa/medusa/common.py", line 422, in quality_from_file_meta
    knowledge = knowit.know(file_path)
  File "/usr/local/share/www/Medusa/lib/knowit/api.py", line 49, in know
    return provider.describe(video_path, context)
  File "/usr/local/share/www/Medusa/lib/knowit/providers/mediainfo.py", line 350, in describe
    video_tracks, audio_tracks, subtitle_tracks, context)
  File "/usr/local/share/www/Medusa/lib/knowit/provider.py", line 35, in _describe_tracks
    props = self._describe_track(general_track, 'general', context)
  File "/usr/local/share/www/Medusa/lib/knowit/provider.py", line 72, in _describe_track
    value = prop.extract_value(track, context)
  File "/usr/local/share/www/Medusa/lib/knowit/property.py", line 33, in extract_value
    value = track.get(names[0], {}).get(names[1]) if len(names) == 2 else track.get(self.name)
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ratoaq2** [comment]
Already fixed in latest version
